  - name: Add the repository of cassandra
    apt_repository:
      repo: deb http://www.apache.org/dist/cassandra/debian 311x main
      filename: cassandra.sources
  - name: Add an apt signing key
    apt_key:
      url: https://www.apache.org/dist/cassandra/KEYS
      state: present
  - name: Install Cassandra  and Update the repo list and Restart cassandra
    apt:
      name: cassandra
      update_cache: yes
      state: present
    notify:
      - Restart cassandra server

  - include: cassandra_config.yml      
  - name: Restart cassandra service
    systemd:
      name: cassandra
      state: restarted
      
