- name: Install java 
  apt:
    name: openjdk-8-jre
    state: present
    update_cache: present
  shell: echo "JAVA_HOME=$(readlink -f /usr/bin/java | sed "s:bin/java::")" | sudo tee -a /etc/profile
  command: source /etc/profile





