 - name: Install java 
   apt:
     name: openjdk-8-jre
     state: present
     update_cache: present
 - name: Java home
   shell: echo "JAVA_HOME=$(readlink -f /usr/bin/java | sed "s:bin/java::")" | sudo tee -a /etc/profile
 - name: source the file
   command: source /etc/profile





